language: python
python:
- '2.7'
install: pip install -r requirements.txt
script:  pwd; cd imagr_site; pwd; python -Wall ./manage.py test
before_install:
- openssl aes-256-cbc -K $encrypted_a3ce96adb379_key -iv $encrypted_a3ce96adb379_iv
  -in imagr_site/imagr_site/credentials.py.enc -out imagr_site/imagr_site/credentials.py -d